name: Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # daily
  workflow_dispatch:      # manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Snake
        uses: platane/snk@v1.0.1
        with:
          github_user_name: syedehsan06
          svg_out_path: github-contribution-grid-snake.svg
